import 'package:sportk/model/countries_model.dart';

List<CountryModel> get kCountries => List<CountryModel>.from(countriesList.map((model) => CountryModel.fromJson(model)));

final countriesList = [
  {"name_en": "Afghanistan", "name_ar": "أفغانستان", "dialCode": "+93", "code": "AF"},
  {"name_en": "Albania", "name_ar": "ألبانيا", "dialCode": "+355", "code": "AL"},
  {"name_en": "Algeria", "name_ar": "الجزائر", "dialCode": "+213", "code": "DZ"},
  {"name_en": "Andorra", "name_ar": "أندورا", "dialCode": "+376", "code": "AD"},
  {"name_en": "Angola", "name_ar": "أنغولا", "dialCode": "+244", "code": "AO"},
  {"name_en": "Antigua and Barbuda", "name_ar": "أنتيغوا وبربودا", "dialCode": "+1 268", "code": "AG"},
  {"name_en": "Argentina", "name_ar": "الأرجنتين", "dialCode": "+54", "code": "AR"},
  {"name_en": "Armenia", "name_ar": "أرمينيا", "dialCode": "+374", "code": "AM"},
  {"name_en": "Australia", "name_ar": "أستراليا", "dialCode": "+61", "code": "AU"},
  {"name_en": "Austria", "name_ar": "النمسا", "dialCode": "+43", "code": "AT"},
  {"name_en": "Azerbaijan", "name_ar": "أذربيجان", "dialCode": "+994", "code": "AZ"},
  {"name_en": "Bahamas", "name_ar": "الباهاما", "dialCode": "+1 242", "code": "BS"},
  {"name_en": "Bahrain", "name_ar": "البحرين", "dialCode": "+973", "code": "BH"},
  {"name_en": "Bangladesh", "name_ar": "بنغلاديش", "dialCode": "+880", "code": "BD"},
  {"name_en": "Barbados", "name_ar": "بربادوس", "dialCode": "+1 246", "code": "BB"},
  {"name_en": "Belarus", "name_ar": "بيلاروسيا", "dialCode": "+375", "code": "BY"},
  {"name_en": "Belgium", "name_ar": "بلجيكا", "dialCode": "+32", "code": "BE"},
  {"name_en": "Belize", "name_ar": "بليز", "dialCode": "+501", "code": "BZ"},
  {"name_en": "Benin", "name_ar": "بنين", "dialCode": "+229", "code": "BJ"},
  {"name_en": "Bhutan", "name_ar": "بوتان", "dialCode": "+975", "code": "BT"},
  {"name_en": "Bolivia", "name_ar": "بوليفيا", "dialCode": "+591", "code": "BO"},
  {"name_en": "Bosnia and Herzegovina", "name_ar": "البوسنة والهرسك", "dialCode": "+387", "code": "BA"},
  {"name_en": "Botswana", "name_ar": "بوتسوانا", "dialCode": "+267", "code": "BW"},
  {"name_en": "Brazil", "name_ar": "البرازيل", "dialCode": "+55", "code": "BR"},
  {"name_en": "Brunei", "name_ar": "بروناي", "dialCode": "+673", "code": "BN"},
  {"name_en": "Bulgaria", "name_ar": "بلغاريا", "dialCode": "+359", "code": "BG"},
  {"name_en": "Burkina Faso", "name_ar": "بوركينا فاسو", "dialCode": "+226", "code": "BF"},
  {"name_en": "Burundi", "name_ar": "بوروندي", "dialCode": "+257", "code": "BI"},
  {"name_en": "Cabo Verde", "name_ar": "الرأس الأخضر", "dialCode": "+238", "code": "CV"},
  {"name_en": "Cambodia", "name_ar": "كمبوديا", "dialCode": "+855", "code": "KH"},
  {"name_en": "Cameroon", "name_ar": "الكاميرون", "dialCode": "+237", "code": "CM"},
  {"name_en": "Canada", "name_ar": "كندا", "dialCode": "+1", "code": "CA"},
  {"name_en": "Central African Republic", "name_ar": "جمهورية أفريقيا الوسطى", "dialCode": "+236", "code": "CF"},
  {"name_en": "Chad", "name_ar": "تشاد", "dialCode": "+235", "code": "TD"},
  {"name_en": "Chile", "name_ar": "تشيلي", "dialCode": "+56", "code": "CL"},
  {"name_en": "China", "name_ar": "الصين", "dialCode": "+86", "code": "CN"},
  {"name_en": "Colombia", "name_ar": "كولومبيا", "dialCode": "+57", "code": "CO"},
  {"name_en": "Comoros", "name_ar": "جزر القمر", "dialCode": "+269", "code": "KM"},
  {"name_en": "Congo (Congo-Brazzaville)", "name_ar": "الكونغو (برازافيل)", "dialCode": "+242", "code": "CG"},
  {"name_en": "Congo, Democratic Republic of the Congo (Kinshasa)", "name_ar": "جمهورية الكونغو الديمقراطية (كينشاسا)", "dialCode": "+243", "code": "CD"},
  {"name_en": "Costa Rica", "name_ar": "كوستاريكا", "dialCode": "+506", "code": "CR"},
  {"name_en": "Croatia", "name_ar": "كرواتيا", "dialCode": "+385", "code": "HR"},
  {"name_en": "Cuba", "name_ar": "كوبا", "dialCode": "+53", "code": "CU"},
  {"name_en": "Cyprus", "name_ar": "قبرص", "dialCode": "+357", "code": "CY"},
  {"name_en": "Czech Republic", "name_ar": "جمهورية التشيك", "dialCode": "+420", "code": "CZ"},
  {"name_en": "Denmark", "name_ar": "الدنمارك", "dialCode": "+45", "code": "DK"},
  {"name_en": "Djibouti", "name_ar": "جيبوتي", "dialCode": "+253", "code": "DJ"},
  {"name_en": "Dominica", "name_ar": "دومينيكا", "dialCode": "+1 767", "code": "DM"},
  {"name_en": "Ecuador", "name_ar": "الإكوادور", "dialCode": "+593", "code": "EC"},
  {"name_en": "Egypt", "name_ar": "مصر", "dialCode": "+20", "code": "EG"},
  {"name_en": "El Salvador", "name_ar": "السلفادور", "dialCode": "+503", "code": "SV"},
  {"name_en": "Equatorial Guinea", "name_ar": "غينيا الاستوائية", "dialCode": "+240", "code": "GQ"},
  {"name_en": "Eritrea", "name_ar": "إريتريا", "dialCode": "+291", "code": "ER"},
  {"name_en": "Estonia", "name_ar": "إستونيا", "dialCode": "+372", "code": "EE"},
  {"name_en": "Eswatini", "name_ar": "إسواتيني", "dialCode": "+268", "code": "SZ"},
  {"name_en": "Ethiopia", "name_ar": "إثيوبيا", "dialCode": "+251", "code": "ET"},
  {"name_en": "Fiji", "name_ar": "فيجي", "dialCode": "+679", "code": "FJ"},
  {"name_en": "Finland", "name_ar": "فنلندا", "dialCode": "+358", "code": "FI"},
  {"name_en": "France", "name_ar": "فرنسا", "dialCode": "+33", "code": "FR"},
  {"name_en": "Gabon", "name_ar": "الغابون", "dialCode": "+241", "code": "GA"},
  {"name_en": "Gambia", "name_ar": "غامبيا", "dialCode": "+220", "code": "GM"},
  {"name_en": "Georgia", "name_ar": "جورجيا", "dialCode": "+995", "code": "GE"},
  {"name_en": "Germany", "name_ar": "ألمانيا", "dialCode": "+49", "code": "DE"},
  {"name_en": "Ghana", "name_ar": "غانا", "dialCode": "+233", "code": "GH"},
  {"name_en": "Greece", "name_ar": "اليونان", "dialCode": "+30", "code": "GR"},
  {"name_en": "Grenada", "name_ar": "غرينادا", "dialCode": "+1 473", "code": "GD"},
  {"name_en": "Guatemala", "name_ar": "غواتيمالا", "dialCode": "+502", "code": "GT"},
  {"name_en": "Guinea", "name_ar": "غينيا", "dialCode": "+224", "code": "GN"},
  {"name_en": "Guinea-Bissau", "name_ar": "غينيا بيساو", "dialCode": "+245", "code": "GW"},
  {"name_en": "Guyana", "name_ar": "غيانا", "dialCode": "+592", "code": "GY"},
  {"name_en": "Haiti", "name_ar": "هايتي", "dialCode": "+509", "code": "HT"},
  {"name_en": "Honduras", "name_ar": "هندوراس", "dialCode": "+504", "code": "HN"},
  {"name_en": "Hungary", "name_ar": "المجر", "dialCode": "+36", "code": "HU"},
  {"name_en": "Iceland", "name_ar": "آيسلندا", "dialCode": "+354", "code": "IS"},
  {"name_en": "India", "name_ar": "الهند", "dialCode": "+91", "code": "IN"},
  {"name_en": "Indonesia", "name_ar": "إندونيسيا", "dialCode": "+62", "code": "ID"},
  {"name_en": "Iran", "name_ar": "إيران", "dialCode": "+98", "code": "IR"},
  {"name_en": "Iraq", "name_ar": "العراق", "dialCode": "+964", "code": "IQ"},
  {"name_en": "Ireland", "name_ar": "أيرلندا", "dialCode": "+353", "code": "IE"},
  {"name_en": "Italy", "name_ar": "إيطاليا", "dialCode": "+39", "code": "IT"},
  {"name_en": "Jamaica", "name_ar": "جامايكا", "dialCode": "+1 876", "code": "JM"},
  {"name_en": "Japan", "name_ar": "اليابان", "dialCode": "+81", "code": "JP"},
  {"name_en": "Jordan", "name_ar": "الأردن", "dialCode": "+962", "code": "JO"},
  {"name_en": "Kazakhstan", "name_ar": "كازاخستان", "dialCode": "+7", "code": "KZ"},
  {"name_en": "Kenya", "name_ar": "كينيا", "dialCode": "+254", "code": "KE"},
  {"name_en": "Kiribati", "name_ar": "كيريباتي", "dialCode": "+686", "code": "KI"},
  {"name_en": "Korea, North", "name_ar": "كوريا الشمالية", "dialCode": "+850", "code": "KP"},
  {"name_en": "Korea, South", "name_ar": "كوريا الجنوبية", "dialCode": "+82", "code": "KR"},
  {"name_en": "Kosovo", "name_ar": "كوسوفو", "dialCode": "+383", "code": "XK"},
  {"name_en": "Kuwait", "name_ar": "الكويت", "dialCode": "+965", "code": "KW"},
  {"name_en": "Kyrgyzstan", "name_ar": "قيرغيزستان", "dialCode": "+996", "code": "KG"},
  {"name_en": "Laos", "name_ar": "لاوس", "dialCode": "+856", "code": "LA"},
  {"name_en": "Latvia", "name_ar": "لاتفيا", "dialCode": "+371", "code": "LV"},
  {"name_en": "Lebanon", "name_ar": "لبنان", "dialCode": "+961", "code": "LB"},
  {"name_en": "Lesotho", "name_ar": "ليسوتو", "dialCode": "+266", "code": "LS"},
  {"name_en": "Liberia", "name_ar": "ليبيريا", "dialCode": "+231", "code": "LR"},
  {"name_en": "Libya", "name_ar": "ليبيا", "dialCode": "+218", "code": "LY"},
  {"name_en": "Liechtenstein", "name_ar": "ليختنشتاين", "dialCode": "+423", "code": "LI"},
  {"name_en": "Lithuania", "name_ar": "ليتوانيا", "dialCode": "+370", "code": "LT"},
  {"name_en": "Luxembourg", "name_ar": "لوكسمبورغ", "dialCode": "+352", "code": "LU"},
  {"name_en": "Madagascar", "name_ar": "مدغشقر", "dialCode": "+261", "code": "MG"},
  {"name_en": "Malawi", "name_ar": "مالاوي", "dialCode": "+265", "code": "MW"},
  {"name_en": "Malaysia", "name_ar": "ماليزيا", "dialCode": "+60", "code": "MY"},
  {"name_en": "Maldives", "name_ar": "جزر المالديف", "dialCode": "+960", "code": "MV"},
  {"name_en": "Mali", "name_ar": "مالي", "dialCode": "+223", "code": "ML"},
  {"name_en": "Malta", "name_ar": "مالطا", "dialCode": "+356", "code": "MT"},
  {"name_en": "Marshall Islands", "name_ar": "جزر مارشال", "dialCode": "+692", "code": "MH"},
  {"name_en": "Mauritania", "name_ar": "موريتانيا", "dialCode": "+222", "code": "MR"},
  {"name_en": "Mauritius", "name_ar": "موريشيوس", "dialCode": "+230", "code": "MU"},
  {"name_en": "Mexico", "name_ar": "المكسيك", "dialCode": "+52", "code": "MX"},
  {"name_en": "Micronesia", "name_ar": "ميكرونيزيا", "dialCode": "+691", "code": "FM"},
  {"name_en": "Moldova", "name_ar": "مولدوفا", "dialCode": "+373", "code": "MD"},
  {"name_en": "Monaco", "name_ar": "موناكو", "dialCode": "+377", "code": "MC"},
  {"name_en": "Mongolia", "name_ar": "منغوليا", "dialCode": "+976", "code": "MN"},
  {"name_en": "Montenegro", "name_ar": "الجبل الأسود", "dialCode": "+382", "code": "ME"},
  {"name_en": "Morocco", "name_ar": "المغرب", "dialCode": "+212", "code": "MA"},
  {"name_en": "Mozambique", "name_ar": "موزمبيق", "dialCode": "+258", "code": "MZ"},
  {"name_en": "Myanmar", "name_ar": "ميانمار", "dialCode": "+95", "code": "MM"},
  {"name_en": "Namibia", "name_ar": "ناميبيا", "dialCode": "+264", "code": "NA"},
  {"name_en": "Nauru", "name_ar": "ناورو", "dialCode": "+674", "code": "NR"},
  {"name_en": "Nepal", "name_ar": "نيبال", "dialCode": "+977", "code": "NP"},
  {"name_en": "Netherlands", "name_ar": "هولندا", "dialCode": "+31", "code": "NL"},
  {"name_en": "New Zealand", "name_ar": "نيوزيلندا", "dialCode": "+64", "code": "NZ"},
  {"name_en": "Nicaragua", "name_ar": "نيكاراغوا", "dialCode": "+505", "code": "NI"},
  {"name_en": "Niger", "name_ar": "النيجر", "dialCode": "+227", "code": "NE"},
  {"name_en": "Nigeria", "name_ar": "نيجيريا", "dialCode": "+234", "code": "NG"},
  {"name_en": "North Macedonia", "name_ar": "مقدونيا الشمالية", "dialCode": "+389", "code": "MK"},
  {"name_en": "Norway", "name_ar": "النرويج", "dialCode": "+47", "code": "NO"},
  {"name_en": "Oman", "name_ar": "عُمان", "dialCode": "+968", "code": "OM"},
  {"name_en": "Pakistan", "name_ar": "باكستان", "dialCode": "+92", "code": "PK"},
  {"name_en": "Palau", "name_ar": "بالاو", "dialCode": "+680", "code": "PW"},
  {"name_en": "Palestine", "name_ar": "فلسطين", "dialCode": "+970", "code": "PS"},
  {"name_en": "Panama", "name_ar": "بنما", "dialCode": "+507", "code": "PA"},
  {"name_en": "Papua New Guinea", "name_ar": "بابوا غينيا الجديدة", "dialCode": "+675", "code": "PG"},
  {"name_en": "Paraguay", "name_ar": "باراغواي", "dialCode": "+595", "code": "PY"},
  {"name_en": "Peru", "name_ar": "بيرو", "dialCode": "+51", "code": "PE"},
  {"name_en": "Philippines", "name_ar": "الفلبين", "dialCode": "+63", "code": "PH"},
  {"name_en": "Poland", "name_ar": "بولندا", "dialCode": "+48", "code": "PL"},
  {"name_en": "Portugal", "name_ar": "البرتغال", "dialCode": "+351", "code": "PT"},
  {"name_en": "Qatar", "name_ar": "قطر", "dialCode": "+974", "code": "QA"},
  {"name_en": "Romania", "name_ar": "رومانيا", "dialCode": "+40", "code": "RO"},
  {"name_en": "Russia", "name_ar": "روسيا", "dialCode": "+7", "code": "RU"},
  {"name_en": "Rwanda", "name_ar": "رواندا", "dialCode": "+250", "code": "RW"},
  {"name_en": "Saint Kitts and Nevis", "name_ar": "سانت كيتس ونيفيس", "dialCode": "+1 869", "code": "KN"},
  {"name_en": "Saint Lucia", "name_ar": "سانت لوسيا", "dialCode": "+1 758", "code": "LC"},
  {"name_en": "Saint Vincent and the Grenadines", "name_ar": "سانت فنسنت وجزر غرينادين", "dialCode": "+1 784", "code": "VC"},
  {"name_en": "Samoa", "name_ar": "ساموا", "dialCode": "+685", "code": "WS"},
  {"name_en": "San Marino", "name_ar": "سان مارينو", "dialCode": "+378", "code": "SM"},
  {"name_en": "Sao Tome and Principe", "name_ar": "ساو تومي وبرينسيبي", "dialCode": "+239", "code": "ST"},
  {"name_en": "Saudi Arabia", "name_ar": "المملكة العربية السعودية", "dialCode": "+966", "code": "SA"},
  {"name_en": "Senegal", "name_ar": "السنغال", "dialCode": "+221", "code": "SN"},
  {"name_en": "Serbia", "name_ar": "صربيا", "dialCode": "+381", "code": "RS"},
  {"name_en": "Seychelles", "name_ar": "سيشل", "dialCode": "+248", "code": "SC"},
  {"name_en": "Sierra Leone", "name_ar": "سيراليون", "dialCode": "+232", "code": "SL"},
  {"name_en": "Singapore", "name_ar": "سنغافورة", "dialCode": "+65", "code": "SG"},
  {"name_en": "Slovakia", "name_ar": "سلوفاكيا", "dialCode": "+421", "code": "SK"},
  {"name_en": "Slovenia", "name_ar": "سلوفينيا", "dialCode": "+386", "code": "SI"},
  {"name_en": "Solomon Islands", "name_ar": "جزر سليمان", "dialCode": "+677", "code": "SB"},
  {"name_en": "Somalia", "name_ar": "الصومال", "dialCode": "+252", "code": "SO"},
  {"name_en": "South Africa", "name_ar": "جنوب أفريقيا", "dialCode": "+27", "code": "ZA"},
  {"name_en": "South Sudan", "name_ar": "جنوب السودان", "dialCode": "+211", "code": "SS"},
  {"name_en": "Spain", "name_ar": "إسبانيا", "dialCode": "+34", "code": "ES"},
  {"name_en": "Sri Lanka", "name_ar": "سريلانكا", "dialCode": "+94", "code": "LK"},
  {"name_en": "Sudan", "name_ar": "السودان", "dialCode": "+249", "code": "SD"},
  {"name_en": "Suriname", "name_ar": "سورينام", "dialCode": "+597", "code": "SR"},
  {"name_en": "Sweden", "name_ar": "السويد", "dialCode": "+46", "code": "SE"},
  {"name_en": "Switzerland", "name_ar": "سويسرا", "dialCode": "+41", "code": "CH"},
  {"name_en": "Syria", "name_ar": "سوريا", "dialCode": "+963", "code": "SY"},
  {"name_en": "Taiwan", "name_ar": "تايوان", "dialCode": "+886", "code": "TW"},
  {"name_en": "Tajikistan", "name_ar": "طاجيكستان", "dialCode": "+992", "code": "TJ"},
  {"name_en": "Tanzania", "name_ar": "تانزانيا", "dialCode": "+255", "code": "TZ"},
  {"name_en": "Thailand", "name_ar": "تايلاند", "dialCode": "+66", "code": "TH"},
  {"name_en": "Timor-Leste", "name_ar": "تيمور الشرقية", "dialCode": "+670", "code": "TL"},
  {"name_en": "Togo", "name_ar": "توغو", "dialCode": "+228", "code": "TG"},
  {"name_en": "Tonga", "name_ar": "تونغا", "dialCode": "+676", "code": "TO"},
  {"name_en": "Trinidad and Tobago", "name_ar": "ترينيداد وتوباغو", "dialCode": "+1 868", "code": "TT"},
  {"name_en": "Tunisia", "name_ar": "تونس", "dialCode": "+216", "code": "TN"},
  {"name_en": "Turkey", "name_ar": "تركيا", "dialCode": "+90", "code": "TR"},
  {"name_en": "Turkmenistan", "name_ar": "تركمانستان", "dialCode": "+993", "code": "TM"},
  {"name_en": "Tuvalu", "name_ar": "توفالو", "dialCode": "+688", "code": "TV"},
  {"name_en": "Uganda", "name_ar": "أوغندا", "dialCode": "+256", "code": "UG"},
  {"name_en": "Ukraine", "name_ar": "أوكرانيا", "dialCode": "+380", "code": "UA"},
  {"name_en": "United Arab Emirates", "name_ar": "الإمارات العربية المتحدة", "dialCode": "+971", "code": "AE"},
  {"name_en": "United Kingdom", "name_ar": "المملكة المتحدة", "dialCode": "+44", "code": "GB"},
  {"name_en": "United States", "name_ar": "الولايات المتحدة", "dialCode": "+1", "code": "US"},
  {"name_en": "Uruguay", "name_ar": "أوروغواي", "dialCode": "+598", "code": "UY"},
  {"name_en": "Uzbekistan", "name_ar": "أوزبكستان", "dialCode": "+998", "code": "UZ"},
  {"name_en": "Vanuatu", "name_ar": "فانواتو", "dialCode": "+678", "code": "VU"},
  {"name_en": "Vatican City", "name_ar": "الفاتيكان", "dialCode": "+39", "code": "VA"},
  {"name_en": "Venezuela", "name_ar": "فنزويلا", "dialCode": "+58", "code": "VE"},
  {"name_en": "Vietnam", "name_ar": "فيتنام", "dialCode": "+84", "code": "VN"},
  {"name_en": "Yemen", "name_ar": "اليمن", "dialCode": "+967", "code": "YE"},
  {"name_en": "Zambia", "name_ar": "زامبيا", "dialCode": "+260", "code": "ZM"},
  {"name_en": "Zimbabwe", "name_ar": "زيمبابوي", "dialCode": "+263", "code": "ZW"}
];
